services:

  # LLM management platform
  ollama: 
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama
    volumes:
      - ~/docker/ollama:/root/.ollama   
      # Mistral 7B lightweight model >> docker exec -it ollama ollama pull mistral
      # Mistral 7B_Q2K lightweight model >> docker exec -it ollama ollama pull mistral:7b-instruct-q2_K
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] # count: all # =  all available GPUs VS GPU 0 as listed by nvidia-smi.
              capabilities: [gpu]
    ports:
      - "11434:11434"
    tty: true
    restart: unless-stopped
    networks:
      - docker_default

  # interactive UI to access ollama functionalities
  open-webui: 
    #image: open-webui:gt1030  # lightweight build for compute capability 6.1 >> \home\autem-dev\open-webui\Dockerfile
    image: ghcr.io/open-webui/open-webui:dev-cuda # for compute capability > 7+ 
    container_name: open-webui
    volumes:
      - /home/autem-dev/docker/owui:/app/backend/data
      # - /mnt/c/Users/[your user]/Documents/Obsidian:/app/synced/obsidian # auto sync to WSL repo \\wsl.localhost\Ubuntu-22.04\mnt\c\Users\[your user]\Documents\Obsidian
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
      - ENABLE_OPENAI=false
    restart: unless-stopped
    networks:
      - docker_default

# document processing and text extraction
  tika:
    image: apache/tika:latest-full
    container_name: tika
    restart: on-failure
    ports:
      - "9998:9998"
    networks:
      - docker_default
    
networks:
  docker_default:
    external: true  # set to true if you're managing this network manually
